### ISSUE TITLE
Plugin installation issues

### ISSUE THREAD

**Issue by welshjf** [deginner/desw#20]
Filing here as it affects all currency plugins.

Currently there's no way to initialize a plugin's hwbalance entry if it's installed as a package; you have to use install.py straight from the git repo or unpacked sdist.

Even if the script were included in packaging, it would still be error-prone as you'd have to remember to set the DESW_CONFIG_FILE environment variable, and besides it seems like an unnecessary deployment complication. DeSW is able to create its tables automatically as needed (using create_all); the plugins should be able to initialize themselves similarly.

**Comment by isysd** [comment]
I believe this is fixed with the new configuration helpers included in v0.0.3.
